services:
  db:
    image: postgres:latest
    container_name: postgres_local
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db_test:
    image: postgres:latest
    container_name: postgres_test
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase_test
    ports:
      - "5433:5432"  # 5433 is the port for the test database
    restart: always

volumes:
  postgres_data:
